### ISSUE TITLE
Error on consolidating library

### ISSUE THREAD

**Issue by mcpierce** [mcpierce/comixed#18]
While consolidating the library the following exception was thrown:

Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:907)
	at java.util.ArrayList$Itr.next(ArrayList.java:857)
	at org.comixed.ui.components.ComicCoverFlowPanel.redisplayCovers(ComicCoverFlowPanel.java:108)
	at org.comixed.ui.components.ComicCoverFlowPanel.selectionChanged(ComicCoverFlowPanel.java:125)
	at org.comixed.library.model.ComicSelectionModel.fireSelectionChangedEvent(ComicSelectionModel.java:87)
	at org.comixed.library.model.ComicSelectionModel.reloadComics(ComicSelectionModel.java:180)
	at org.comixed.library.model.ComicSelectionModel.getComicCount(ComicSelectionModel.java:130)
	at org.comixed.library.model.ComicTableModel.getRowCount(ComicTableModel.java:150)
	at javax.swing.JTable.getRowCount(JTable.java:2662)
	at javax.swing.plaf.basic.BasicTableUI.createTableSize(BasicTableUI.java:1692)
	at javax.swing.plaf.basic.BasicTableUI.getPreferredSize(BasicTableUI.java:1733)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at java.awt.Container.layout(Container.java:1510)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validate(Container.java:1630)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by mcpierce** [comment]
Closing this as probably related to the old non-web codebase.
