### ISSUE TITLE
Exception thrown when scraping a comic

### ISSUE THREAD

**Issue by mcpierce** [mcpierce/comixed#221]
**Describe the bug**
Trying to scrape the details for a comic is resulting in an exception being thrown.

**To Reproduce**
This bug is consistent for the same comic.

**Additional context**
```
2018-10-07 12:33:52.401 ERROR 28424 --- [nio-7171-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.comixed.web.comicvine.ComicVineAdaptorException: failed to process volume response] with root cause

com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: [B@c8dec52; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.8.jar!/:2.8.8]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.8.jar!/:2.8.8]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456) ~[jackson-core-2.8.8.jar!/:2.8.8]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2689) ~[jackson-core-2.8.8.jar!/:2.8.8]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878) ~[jackson-core-2.8.8.jar!/:2.8.8]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772) ~[jackson-core-2.8.8.jar!/:2.8.8]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3834) ~[jackson-databind-2.8.8.jar!/:2.8.8]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783) ~[jackson-databind-2.8.8.jar!/:2.8.8]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2929) ~[jackson-databind-2.8.8.jar!/:2.8.8]
	at org.comixed.web.comicvine.ComicVineVolumesResponseProcessor.process(ComicVineVolumesResponseProcessor.java:147) ~[classes!/:0.2.0-RC1]
	at org.comixed.web.comicvine.ComicVineQueryForVolumesAdaptor.execute(ComicVineQueryForVolumesAdaptor.java:73) ~[classes!/:0.2.0-RC1]
	at org.comixed.web.controllers.ComicVineScraperController.queryForVolumes(ComicVineScraperController.java:88) ~[classes!/:0.2.0-RC1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
```

**Comment by mcpierce** [comment]
This bug is due to the ComicVine API returning HTML (it's blocking scraping ATM) instead of JSON.
