### ISSUE TITLE
Failed During Build

### ISSUE THREAD

**Issue by CDarwin7** [mcpierce/comixed#600]
I get about 1/2 through the build process after MVN Clean Package. It fails with the following, Am I doing something wrong?

Results:
[INFO]
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for comixed-parent 0.4.9-SNAPSHOT:
[INFO]
[INFO] comixed-parent ..................................... SUCCESS [  1.876 s]
[INFO] comixed-library .................................... SUCCESS [08:57 min]
[INFO] comixed-tasks ...................................... FAILURE [01:02 min]
[INFO] comixed-services ................................... SKIPPED
[INFO] comixed-rest-api ................................... SKIPPED
[INFO] comixed-frontend ................................... SKIPPED
[INFO] comixed-app ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:04 min
[INFO] Finished at: 2019-11-11T11:37:47-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project comixed-tasks: There are test failures.
[ERROR]
[ERROR] Please refer to C:\comixed-develop\comixed-develop\comixed-tasks\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C "C:\Progra~1\Java\jdk-10.0.2\bin\java -jar C:\Users\CONANS~1\AppData\Local\Temp\surefire15689902341599360676\surefirebooter5559580467069869044.jar C:\Users\Conansbug\AppData\Local\Temp\surefire15689902341599360676 2019-11-11T11-28-19_180-jvmRun1 surefire15806001685225163444tmp surefire_12963704426958939238tmp"
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] org.comixed.task.model.QueueComicsWorkerTaskTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C "C:\Progra~1\Java\jdk-10.0.2\bin\java -jar C:\Users\CONANS~1\AppData\Local\Temp\surefire15689902341599360676\surefirebooter5559580467069869044.jar C:\Users\Conansbug\AppData\Local\Temp\surefire15689902341599360676 2019-11-11T11-28-19_180-jvmRun1 surefire15806001685225163444tmp surefire_12963704426958939238tmp"
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] org.comixed.task.model.QueueComicsWorkerTaskTest
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

**Comment by bareheiny** [comment]
I can't find where, but Darryl suggested I used "mvn clean install -DskipTests" when compiling CX on a windows machine.

I was getting test failures that were likely similar to yours - haven't struck any problems compiling, or using, CX this way.

**Comment by CDarwin7** [comment]
OK. I will try this and report back.

**Comment by mcpierce** [comment]
@CDarwin7 You're not doing anything wrong. I'm assuming you're running on Windows since that's the only platform I've seen this issue occur nearly consistently. The long of it is that the JVM on Windows has problems with spawning threads during JUnit test runs, and the comixed-tasks module uses ConcurrentUnit to run some threading-related tests.

So on Windows the comixed-tasks module almost always fails to build because the VM  falls down.

So like @bareheiny said, I'd recommend using the **-DskipTests** flag when just compiling on Windows in order to run things. That is, until I get the time to rework the comixed-tasks module and see what else I can do to test those thread-related classes.

**Comment by mcpierce** [comment]
@CDarwin7 ping - are things working better for you now? If so, could you close this ticket? Thanks.

**Comment by jmcrfp** [comment]
I'm also compiling on windows with tests and I don't see that error, but I'm using gitbash.
Try using gitbash or WSL for compiling on windows.
